import fs from 'fs'
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const Home: NextPage<any> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
        {props.bookmarks.map((item) => (
          <li><a href={item}>{item}</a></li>
        ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        created by Sassy.
      </footer>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async ()  => {
  const bookmarks = fs.readFileSync(process.cwd() + '/docs/bookmark.txt', 'utf8').trim().split(/\n/);

  return {
    props: {
      bookmarks : bookmarks
    },
  }
}
